export const DOM = {
    addBtn: document.querySelector('#btn-add'),
    elementPicker: document.querySelector('#test'),
    userResult: document.querySelector('#result'),
    referenceFrom: document.querySelector('#reference-from'),
    referenceTo: document.querySelector('#reference-to'),
    removeElementBtn: document.querySelector('#btn-delete'),
    elementsList: document.querySelectorAll('.elements-list'),
    noTestsBox: document.querySelector('.notests-box'),
    userTests: document.querySelector('.user-tests'),
    addAnotherTestBtn: document.querySelector('#btn-add-new'),
    datePicker: document.querySelector('#test-date'),
    testLocation: document.querySelector('#test-location'),
    enlargeBtn: document.querySelector('#icon-enlarge'),
    container: document.querySelector('.container'),
    containerEnlarged: document.querySelector('.container-enlarged'),
    shrinkBtn: document.querySelector('#icon-shrink'),
    navigationPanel: document.querySelector('.navigation-panel'),
    okBtn: document.querySelector('#btn-ok'),
    userTestsItem: document.querySelector('.user-tests__item'),
    userTestsOptions: document.querySelector('.user-tests__options'),
  }